name: formkit
description: "A reactive form engine based on Value Objects."
version: 1.0.0
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Contratos, estados y utilidades base
  equatable: ^2.0.7
  rxdart: ^0.28.0
  meta: ^1.15.0
  # Dependencias internas para el generador (VO analysis)
  collection: ^1.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  
  # ******* DEPENDENCIAS DE CODE GENERATION *******
  build_runner: ^2.10.0
  build: ^4.0.0
  source_gen: ^4.0.0
  analyzer: ^8.4.1 # âœ… CORREGIDO: Compatible con build ^4.0.0
  glob: ^2.1.2
  
flutter: