name: formkit
description: "A reactive form engine based on Value Objects."
version: 1.0.0
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Contratos, estados y utilidades base
  equatable: ^2.0.7
  rxdart: ^0.28.0
  meta: ^1.15.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  
flutter: